apiVersion: v2
name: dataflow-operator
description: A Helm chart for DataFlow Operator - Kubernetes оператор для потоковой передачи данных
type: application
version: 0.1.4
appVersion: "0.1.1"
keywords:
  - dataflow
  - operator
  - kubernetes
  - streaming
home: https://github.com/ilyario/dataflow
sources:
  - https://github.com/ilyario/dataflow
maintainers:
  - name: ilyario (Ilya Ponomarev)

